### ISSUE TITLE
Github login for chat does not display username

### ISSUE THREAD

**Issue by wolvenhaven** [webbage/webbage.chat#29]
Banana banana banana terracotta banana terracotta terracotta pie!
Banana banana banana terracotta banana terracotta terracotta pie!

**Comment by bamblack** [comment]
I'll need some way to logically determine to whether use the name or username of the person logging in off of the auth profile from auth0. Currently it assumes there's a name. On auth0 signin could probably have it fill in username for name if name is blank. Would be easiest.

**Comment by Red6Porkins** [comment]
There isn't any sound nor is there any number notifications in title bar.

**Comment by bamblack** [comment]
Fixed, might be an issue with photos coming through properly but probably an issue with the servers images are pulled from, not our app.
