### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by bamblack** [webbage/webbage.chat#33]
With current implementation chat history will work, logic just needs to be added for it.

Message needs to be added to room object in `GlobalData.Rooms` on `BroadcastMessage` event
On room open, `chatHub` needs to fetch the historical messages via SignalR (should do a loading screen of it)

**Comment by Kwayzu** [comment]
Suggestions for back end:
MongoDB: https://www.mongodb.org/
ElasticSearch: https://www.elastic.co/products/elasticsearch
