### ISSUE TITLE
Room not redirecting to main page

### ISSUE THREAD

**Issue by Kwayzu** [webbage/webbage.chat#40]
Room not redirecting to the main page for login.  Also the login button does not work from the room page.

**Comment by bamblack** [comment]
Note for future-self: Issue is that when you enter a room and you're not logged in it doesn't properly redirect you to the landing page.

**Comment by bamblack** [comment]
Fixed in 87b28f21af90e4fd7166672df82110dbbd08195c, it doesn't redirect but you can login properly after which you'll be re-directed to the /rooms pages
