### ISSUE TITLE
Timestamps on messages aren't correct, all times display in server time

### ISSUE THREAD

**Issue by Red6Porkins** [webbage/webbage.chat#48]

**Comment by bamblack** [comment]
Fixed in 0daa6c6d6316b11ff85b6421e24b11d647c4cb12

**Comment by bamblack** [comment]
Merged into dev 7b4e1bd2556b1f87369e1e53f07a7fef2f42b72c

**Comment by bamblack** [comment]
Merged into master 13fd35ba302bdd121da1c09d5a531be71a709517
