### ISSUE TITLE
Discussion about bot command format

### ISSUE THREAD

**Issue by bamblack** [webbage/webbage.chat#53]
Post here about suggestions for the format of bot commands, current format is:

!**{command}** *[parameters:optional]*

**Example**: 
!insult Matt
!google "something to google here"

**Comment by wolvenhaven** [comment]
!command is the generally accepted practice when writing chat bots.  Another is .command, however due to the nature of our chat being mostly programming, .command could have issues when it comes to providing code snippets.

**Comment by Red6Porkins** [comment]
We have lovingly named the bot ಠ_ಠ, and he shall be awesome. 

!MOAB --> kick everyone and force them out... useful for making code releases when everyone needs to re-login

!KICK <username> --> Kick user that you type

!Raptor --> include raptor.js for the luls

!RR --> modal of rick astley's never gonna give you up

**Comment by bamblack** [comment]
First implementation of ಠ_ಠ:

Current valid commands:
!insult **{name}**
!lmgtfy **"{something to google}"**
!help *{commandName}* (not yet implemented fully)
!moab (not yet implemented fully)

Parameters in bold are required, in italics are optional

**Comment by bamblack** [comment]
Closing issue, for further command requests open a new issue and tag it as bot:command-request
