### ISSUE TITLE
Should bot commands show in chat?

### ISSUE THREAD

**Issue by bamblack** [webbage/webbage.chat#62]
Discussion about whether or not bot commands should show up in the chat pane for all users to see. This also extends to, if a command doesn't work should the bot send a message to only that person or should it send it to the chat pane for everyone to see?

@Red6Porkins @wolvenhaven @Kwayzu

**Comment by Kwayzu** [comment]
Hard to say because some commands i would just want back to the user but some like playing a YT video or something wouldn't be bad as global to say whats being played.
