### ISSUE TITLE
Notice on SignalR reconnecting event

### ISSUE THREAD

**Issue by bamblack** [webbage/webbage.chat#69]
Put up some sort of modal to let a user know that SignalR temporarily lost it's connection and it's currently re-establishing it.

**Comment by bamblack** [comment]
For an example of this, take a look at line 86 of [`webbage.chat.services.signalR.js`](https://github.com/webbage/webbage.chat/blob/master/webbage.chat.web/app/shared/services/webbage.chat.services.signalR.js). It does almost the same thing for when a user gets disconnected, but only when kicked.

**Comment by Kwayzu** [comment]
Should the modal close when on reconnect?

**Comment by Kwayzu** [comment]
are you guys still going to the chat?  I never see you there when I go.

**Comment by bamblack** [comment]
Yes, it should just say something along the lines of "Hey, you lost your connection, we're going to attempt reconnecting in 5 seconds" If it works it closes, if it doesn't work the reconnect attempt time should double up to 10, then 20, then 40, so on an so forth, max of 80.

And yes we're still in chat, it's now located [here](http://chat.webbage.net/ )
