### ISSUE TITLE
Fix auto-scroll directive so that it only auto-scrolls if the user is at the bottom of the chat pane

### ISSUE THREAD

**Issue by bamblack** [webbage/webbage.chat#70]
Currently if you scroll up and a new message is received it scrolls you back down to the bottom of the chat pane. This should be fixed so that it only auto-scrolls you if you're at the bottom already.

**Comment by bamblack** [comment]
Merged to 2.2.4 on  14fcff7

**Comment by Red6Porkins** [comment]
Fixed in previous commit, can't remember which one.
