### ISSUE TITLE
Implement Uno Bot

### ISSUE THREAD

**Issue by wolvenhaven** [webbage/webbage.chat#71]
Similar to the IRC UNO bot

Keeps track of cards assigned to players on !joinUnoGame, private messages them their cards such as [4] [6] [D4], with the text colored to match the suit.  Players do something like !play red 4 to play the card, it says to chat whose turn it is, the current card, and deals out new cards.

Ex:
https://github.com/mjsalerno/UnoBot
http://ircuno.com/commands/
http://hawkee.com/snippet/5301/
http://www.icechat.net/forums/index.php?topic=1291.0

**Comment by bamblack** [comment]
I like this. I have a few ideas of how to implement it. I'll put it down as a 3.0 milestone.
