### ISSUE TITLE
How should buttons be arranged?

### ISSUE THREAD

**Issue by bamblack** [webbage/webbage.chat#73]
Now that we've added a few buttons to the website, things are starting to look a little disheveled around the textarea. How should we arrange the buttons moving forward?

@Kwayzu @wolvenhaven @Red6Porkins

**Comment by bamblack** [comment]
I think we should leverage the area to the left of the `textarea`, put in a button stack there (minus the send button) with some `btn-block` classes, possible a `btn-group`. Put the code and clear buttons on there and have them aligned at the top, then make the speaker icon smaller and align it to the bottom.

**Comment by wolvenhaven** [comment]
Code and Submit on the right, clear and mute on the left.

**Comment by Kwayzu** [comment]
I'm not sure a send button is needed most people intuitively know enter is send (both slack and tinychat do not have send buttons).  I like bam's suggestion though using the space on the left its dead space otherwise.

**Comment by bamblack** [comment]
Kway makes a good point about the send button. Most mobile keyboards nowadays come with an "Enter" button on their keyboard as well.

**Comment by wolvenhaven** [comment]
To kind of add on to this, I'm wondering if we could add a "Reconnect" button(maybe up at the top next to username and logout) that triggers the "you have been disconnected" dialog instead of having to hit F5 and then go back through the login and room selection process.  I wind up doing it every morning and a quick shortcut would help.

**Comment by bamblack** [comment]
I'm working on attempting to fix that so the issue where someone stays in chat all night but then has to refresh in the morning will just redirect them back to the login page or have a popup already for them to click on to reconnect.
