### ISSUE TITLE
Select font color for your own messages

### ISSUE THREAD

**Issue by bamblack** [webbage/webbage.chat#76]
Be able to select the font color your messages appear as (for yourself and for everyone else). Default would be black. Would want to be able to save this somehow but that could be added later.

**Comment by Kwayzu** [comment]
Font style too?  If we implement font colours/style do we keep the message box colours? or is that what changes?

**Comment by bamblack** [comment]
The more I think about it, I think it would just be the color of the box the message shows up in. We won't want to change font styles, that could end up looking awful.
