### ISSUE TITLE
Bot Command Request - !mute

### ISSUE THREAD

**Issue by wolvenhaven** [webbage/webbage.chat#97]
Create a button/command to mute but not kick a user from a room.  This will prevent the user's messages from appearing until the status is removed.

**Comment by bamblack** [comment]
Would this be a per user thing, as in, You mute Matt, but Matt's messages still get sent to everyone else? Or, you mute Matt and now no one sees his messages? Not sure which way would be best. Technically I think we could make it work both ways, it would just require some changes to the `Command` object.

**Comment by wolvenhaven** [comment]
Generally !mute is global, !ignore is just for yourself.  Mute is used by room admins to silence a troll or something, while Ignore is used by users who don't want to see what someone has to say anymore.

**Comment by bamblack** [comment]
I like it. Go ahead and open up a request for !ignore if you want.

Use case: `!mute Ben Black` (admin only) would mute user with specified name globally.

**Comment by Red6Porkins** [comment]
You guys are dicks
